(function applyCurrentCvCopy(global) {
  const cv = {
    en: {
      navResume: "CV",
      viewResume: "View CV",
      readResume: "Read my CV",
      closeResume: "Close CV",
      resumeTopline: "Curriculum Vitae (CV)",
      printResume: "Print / Save CV",
      resumeFocus: "UX Research | Interaction Design | Human-Computer Interaction",
      resumeSummary: "Bachelor of Design candidate at the University of Melbourne, with completed coursework and practical experience in applied psychology, UX research, interaction design, and mixed methods. My work has included questionnaire development, interviews, usability testing, survey-data cleaning, initial descriptive analysis, open-text coding, research reporting, and interactive Figma prototyping.",
      resumeProfileTitle: "Research Profile",
      resumeProfileOne: "Bachelor of Design candidate at the University of Melbourne, with completed coursework and practical experience in applied psychology, UX research, interaction design, and mixed methods. My work has included questionnaire development, interviews, usability testing, survey-data cleaning, initial descriptive analysis, open-text coding, research reporting, and interactive Figma prototyping.",
      resumeProfileTwo: "My future research direction grows from a question that now drives my interest in embodied interaction, namely how people can perceive gradual changes in their own bodies when progress is too slow to notice day by day. I hope to explore whether a person's past exertion-related bodily state can be recorded, calibrated, and replayed across sessions so that rehabilitation progress becomes easier to perceive. This is research I want to pursue rather than work I have already completed. Graduate study would allow me to build the necessary capabilities in wearable sensing, psychophysics, haptic prototyping, longitudinal evaluation, and research ethics, beginning with technical calibration and healthy-adult studies before considering rehabilitation feasibility.",
      educationTitle: "Education",
      educationOneDate: "Feb 2024 - Expected Feb 2027",
      educationOneDegree: "The University of Melbourne | Bachelor of Design",
      educationOnePlace: "Melbourne, Australia",
      educationOneFocus: "Focus: Human-Computer Interaction and User Experience Design.",
      educationOneBody: "Relevant coursework: User Research, Quantitative and Qualitative Research, Usability Evaluation, Web and Interaction Design, Finance, and Business.",
      educationTwoDate: "Jul 2025 - Aug 2025",
      educationTwoDegree: "Korea University | Short-Term Exchange Study",
      educationTwoPlace: "Seoul, South Korea",
      educationTwoBody: "Cross-cultural study and international academic experience.",
      educationThreeDate: "Jan 2026 - Feb 2026",
      educationThreeDegree: "Ritsumeikan University | Short-Term Exchange Study",
      educationThreePlace: "Kyoto, Japan",
      educationThreeBody: "Japanese language and culture study in an international learning environment.",
      experienceTitle: "Research & Relevant Experience",
      experienceOneDate: "Feb 2026 - Jun 2026",
      experienceOneRole: "HCI Research Assistant",
      experienceOnePlace: "The University of Melbourne",
      experienceOneSubtitle: "AI-Supported Education and Student Course Experience Research Project",
      experienceOneBulletOne: "Supported an education research project examining how AI tools could be integrated into university teaching to improve student course experience and teaching quality.",
      experienceOneBulletTwo: "Helped develop a mixed-method course-satisfaction questionnaire with quantitative scales and open-ended items; organised and cleaned responses, conducted initial descriptive analysis, and coded qualitative feedback.",
      experienceOneBulletThree: "Joined university research meetings and prepared charts, report drafts, and presentation materials that connected student feedback with HCI questions around AI-supported learning.",
      experienceTwoDate: "Feb 2025 - Jul 2025",
      experienceTwoRole: "UI/UX Design Intern",
      experienceTwoPlace: "TidyTeddy",
      experienceTwoBulletOne: "Worked on a project to update TidyTeddy's cleaning-services website and develop new functions, starting with sketches, button placement, page structure, and low-fidelity web and mobile prototypes.",
      experienceTwoBulletTwo: "Converted the approved flows into high-fidelity web and mobile prototypes in Figma, defining responsive layouts, component states, navigation, and handoff specifications.",
      experienceTwoBulletThree: "Coordinated design handoff and implementation feedback with the IT team, revised the interface during development, and supported the formal launch of the updated website and new features.",
      experienceThreeDate: "May 2026 - Present",
      experienceThreeRole: "Product Manager / Digital Consultant",
      experienceThreePlace: "Linghang Education & Migration Service",
      experienceThreeBulletOne: "Mapped back-office study-abroad and migration workflows, identified repetitive research and document tasks, and designed UiPath/RPA and AI-assisted processes with Codex to reduce manual work in information collection, checking, template use, and knowledge reuse.",
      experienceThreeBulletTwo: "Designed study-abroad service packages by translating client goals, academic background, eligibility, timelines, and risks into service options and task plans; applied source verification, human review, privacy controls, and exception handling to AI-supported work.",
      resumeProjectsTitle: "Selected Research Projects",
      resumeProjectOneDate: "Feb 2026 - Jun 2026",
      resumeProjectOneTitle: "AI-Supported Education and Student Course Experience Study | University of Melbourne",
      resumeProjectOneBulletOne: "Contributed to a mixed-method education research project examining student course satisfaction and how AI tools might support university teaching, helping structure evaluation dimensions and questionnaire items.",
      resumeProjectOneBulletTwo: "Organised and cleaned survey responses, conducted initial descriptive analysis, coded open-text feedback, and prepared charts, report drafts, and presentation materials for university research meetings.",
      resumeProjectTwoDate: "2024 - 2026",
      resumeProjectTwoTitle: "User Research and Behavioural Analysis | University Coursework",
      resumeProjectTwoBulletOne: "Used questionnaires, interviews, observation, and task analysis to examine users' goals, behaviours, constraints, satisfaction, and decision paths across digital products and services.",
      resumeProjectTwoBulletTwo: "Synthesised evidence into personas, journey maps, task flows, pain points, and prioritised research and design opportunities.",
      resumeProjectThreeDate: "2024 - 2026",
      resumeProjectThreeTitle: "Usability Evaluation and Accessibility | University Coursework",
      resumeProjectThreeBulletOne: "Evaluated websites and digital platforms through usability testing, first-click tests, five-second tests, and card sorting, examining task efficiency, errors, friction, and comprehension.",
      resumeProjectThreeBulletTwo: "Applied Nielsen's heuristics, WAI accessibility guidance, and ISO 9241 principles to diagnose interface problems and prioritise design recommendations.",
      resumeProjectFourDate: "2024 - 2026",
      resumeProjectFourTitle: "Web Interaction Design and Prototyping | University Coursework",
      resumeProjectFourBulletOne: "Designed information architecture, responsive page layouts, visual hierarchy, interface states, and interaction flows in Figma.",
      resumeProjectFourBulletTwo: "Built and tested interactive prototypes and developed foundational HTML, CSS, and JavaScript knowledge for collaboration across design and development.",
      resumeProjectFiveDate: "Feb 2025 - Jun 2025",
      resumeProjectFiveTitle: "Quantitative Decision Analysis | Australian Multi-Asset Strategy",
      resumeProjectFiveBulletOne: "Analysed 2013-2024 annual data for 10 Australian asset classes in Excel, comparing mean returns, volatility, compound annual growth, Sharpe ratios, and interest-rate stress scenarios to form a risk-aware allocation recommendation.",
      resumeProjectSixDate: "2025 - 2026",
      resumeProjectSixTitle: "Human-AI Workflow Design and Product Testing",
      resumeProjectSixBulletOne: "Examined how generative AI and RPA can support information collection, synthesis, template building, visual exploration, and product testing while retaining source verification, human review, privacy protection, and exception handling.",
      resumeCapabilitiesTitle: "Research, Design & Technical Skills",
      resumeCapabilityOneTitle: "UX Research",
      resumeCapabilityOneBody: "Questionnaire development, qualitative interviews, observation, task analysis, usability testing, first-click testing, five-second testing, card sorting, eye-tracking testing, and accessibility evaluation.",
      resumeCapabilityTwoTitle: "Interaction Design & Prototyping",
      resumeCapabilityTwoBody: "Personas, journey maps, information architecture, wireframing, responsive interface design, and interactive Figma prototyping.",
      resumeCapabilityThreeTitle: "Data Analysis",
      resumeCapabilityThreeBody: "Survey-data cleaning, descriptive statistics, open-text coding, thematic analysis, charting, and data visualisation in Excel.",
      resumeCapabilityFourTitle: "Programming & AI Automation",
      resumeCapabilityFourBody: "HTML, CSS, and JavaScript; AI-assisted workflow design, UiPath/RPA, Codex, ChatGPT, source verification, human review, and exception handling.",
      resumeCapabilityFiveTitle: "Project Delivery",
      resumeCapabilityFiveBody: "Research planning, requirements definition, research meetings, stakeholder communication, service-journey mapping, design handoff, and cross-functional delivery.",
      resumeCapabilitySixTitle: "Languages",
      resumeCapabilitySixBody: "Mandarin Chinese (native), English (fluent), and Japanese (basic).",
    },
    zh: {
      navResume: "CV",
      viewResume: "查看 CV",
      readResume: "阅读我的 CV",
      closeResume: "关闭 CV",
      resumeTopline: "学术履历（CV）",
      printResume: "打印 / 保存 CV",
      resumeFocus: "用户体验研究 | 交互设计 | 人机交互",
      resumeSummary: "墨尔本大学设计学学士在读，已完成应用心理学、用户体验研究、交互设计与混合研究方法相关课程，并具备相应实践经历。我的工作包括问卷设计、访谈、可用性测试、问卷数据清洗、初步描述性分析、开放文本编码、研究报告和 Figma 交互原型制作。",
      resumeProfileTitle: "研究简介",
      resumeProfileOne: "墨尔本大学设计学学士在读，已完成应用心理学、用户体验研究、交互设计与混合研究方法相关课程，并具备相应实践经历。我的工作包括问卷设计、访谈、可用性测试、问卷数据清洗、初步描述性分析、开放文本编码、研究报告和 Figma 交互原型制作。",
      resumeProfileTwo: "我未来的研究方向来自一个目前推动我关注身体交互的问题：当身体的进步缓慢到难以逐日察觉时，人们如何感知自身身体正在发生的渐进变化。我希望探索一个人过去与运动负荷相关的身体状态能否被记录、校准，并在不同训练阶段之间重现，从而让康复进展更容易被感知。这是我希望未来开展的研究，而不是已经完成的工作。研究生阶段的学习将帮助我建立可穿戴感知、心理物理学、触觉原型、纵向评估和研究伦理方面所需的能力；研究将从技术校准和健康成年人研究开始，再考虑康复应用的可行性。",
      educationTitle: "教育经历",
      educationOneDate: "2024年2月 - 预计2027年2月",
      educationOneDegree: "墨尔本大学 | 设计学学士",
      educationOnePlace: "澳大利亚，墨尔本",
      educationOneFocus: "方向：人机交互与用户体验设计。",
      educationOneBody: "相关课程：用户研究、定量与定性研究、可用性评估、网页与交互设计、金融与商业。",
      educationTwoDate: "2025年7月 - 2025年8月",
      educationTwoDegree: "高丽大学 | 短期交换学习",
      educationTwoPlace: "韩国，首尔",
      educationTwoBody: "跨文化学习与国际学术经历。",
      educationThreeDate: "2026年1月 - 2026年2月",
      educationThreeDegree: "立命馆大学 | 短期交换学习",
      educationThreePlace: "日本，京都",
      educationThreeBody: "在国际化学习环境中学习日语与日本文化。",
      experienceTitle: "研究及相关经历",
      experienceOneDate: "2026年2月 - 2026年6月",
      experienceOneRole: "HCI 研究助理",
      experienceOnePlace: "墨尔本大学",
      experienceOneSubtitle: "AI 辅助教育与学生课程体验研究项目",
      experienceOneBulletOne: "参与一项教育研究项目，考察如何将 AI 工具融入大学教学，以改善学生课程体验与教学质量。",
      experienceOneBulletTwo: "协助设计一份混合方法课程满意度问卷，包含定量量表和开放题；整理并清洗问卷回答，进行初步描述性分析，并编码定性反馈。",
      experienceOneBulletThree: "参加大学研究会议，制作图表、报告初稿和演示材料，将学生反馈与 AI 辅助学习相关的 HCI 问题联系起来。",
      experienceTwoDate: "2025年2月 - 2025年7月",
      experienceTwoRole: "UI/UX 设计实习生",
      experienceTwoPlace: "TidyTeddy",
      experienceTwoBulletOne: "参与更新 TidyTeddy 清洁服务网站并开发新功能，从草图、按钮位置、页面结构以及低保真网页和移动端原型开始推进。",
      experienceTwoBulletTwo: "将获批流程转化为 Figma 高保真网页和移动端原型，定义响应式布局、组件状态、导航和交付规范。",
      experienceTwoBulletThree: "与 IT 团队协调设计交付和实施反馈，在开发期间调整界面，并支持更新后的网站与新功能正式上线。",
      experienceThreeDate: "2026年5月 - 至今",
      experienceThreeRole: "产品经理 / 数字化顾问",
      experienceThreePlace: "领航教育与移民服务",
      experienceThreeBulletOne: "梳理留学与移民后台流程，识别重复性的研究与文档任务，并使用 UiPath/RPA 和 Codex 设计 AI 辅助流程，减少信息收集、核查、模板使用和知识复用中的人工工作。",
      experienceThreeBulletTwo: "将客户目标、学术背景、资格条件、时间线与风险转化为服务选项和任务计划，设计留学服务方案；在 AI 辅助工作中采用来源核验、人工复核、隐私控制与例外处理。",
      resumeProjectsTitle: "精选研究项目",
      resumeProjectOneDate: "2026年2月 - 2026年6月",
      resumeProjectOneTitle: "AI 辅助教育与学生课程体验研究 | 墨尔本大学",
      resumeProjectOneBulletOne: "参与一项混合方法教育研究，考察学生课程满意度以及 AI 工具如何支持大学教学，并协助构建评估维度和问卷题目。",
      resumeProjectOneBulletTwo: "整理并清洗问卷回答，进行初步描述性分析，编码开放文本反馈，并为大学研究会议准备图表、报告初稿和演示材料。",
      resumeProjectTwoDate: "2024年 - 2026年",
      resumeProjectTwoTitle: "用户研究与行为分析 | 大学课程项目",
      resumeProjectTwoBulletOne: "使用问卷、访谈、观察和任务分析，考察用户在不同数字产品与服务中的目标、行为、限制、满意度和决策路径。",
      resumeProjectTwoBulletTwo: "将证据整理为用户画像、旅程地图、任务流程、痛点以及有优先级的研究与设计机会。",
      resumeProjectThreeDate: "2024年 - 2026年",
      resumeProjectThreeTitle: "可用性评估与无障碍 | 大学课程项目",
      resumeProjectThreeBulletOne: "通过可用性测试、首次点击测试、五秒测试和卡片分类评估网站及数字平台，考察任务效率、错误、阻碍和理解程度。",
      resumeProjectThreeBulletTwo: "运用 Nielsen 启发式原则、WAI 无障碍指南和 ISO 9241 原则诊断界面问题，并确定设计建议的优先级。",
      resumeProjectFourDate: "2024年 - 2026年",
      resumeProjectFourTitle: "网页交互设计与原型 | 大学课程项目",
      resumeProjectFourBulletOne: "在 Figma 中设计信息架构、响应式页面布局、视觉层级、界面状态和交互流程。",
      resumeProjectFourBulletTwo: "制作并测试交互原型，同时建立 HTML、CSS 和 JavaScript 基础知识，以支持设计与开发之间的协作。",
      resumeProjectFiveDate: "2025年2月 - 2025年6月",
      resumeProjectFiveTitle: "定量决策分析 | 澳大利亚多资产策略",
      resumeProjectFiveBulletOne: "在 Excel 中分析 10 类澳大利亚资产 2013-2024 年的年度数据，比较平均回报、波动率、复合年增长、夏普比率和利率压力情景，以形成兼顾风险的配置建议。",
      resumeProjectSixDate: "2025年 - 2026年",
      resumeProjectSixTitle: "人机协作流程设计与产品测试",
      resumeProjectSixBulletOne: "考察生成式 AI 与 RPA 如何支持信息收集、综合、模板制作、视觉探索和产品测试，同时保留来源核验、人工复核、隐私保护和例外处理。",
      resumeCapabilitiesTitle: "研究、设计与技术技能",
      resumeCapabilityOneTitle: "用户体验研究",
      resumeCapabilityOneBody: "问卷设计、定性访谈、观察、任务分析、可用性测试、首次点击测试、五秒测试、卡片分类、眼动测试与无障碍评估。",
      resumeCapabilityTwoTitle: "交互设计与原型",
      resumeCapabilityTwoBody: "用户画像、旅程地图、信息架构、线框图、响应式界面设计与 Figma 交互原型。",
      resumeCapabilityThreeTitle: "数据分析",
      resumeCapabilityThreeBody: "问卷数据清洗、描述性统计、开放文本编码、主题分析、图表制作和 Excel 数据可视化。",
      resumeCapabilityFourTitle: "编程与 AI 自动化",
      resumeCapabilityFourBody: "HTML、CSS 与 JavaScript；AI 辅助流程设计、UiPath/RPA、Codex、ChatGPT、来源核验、人工复核和例外处理。",
      resumeCapabilityFiveTitle: "项目交付",
      resumeCapabilityFiveBody: "研究规划、需求定义、研究会议、利益相关者沟通、服务旅程梳理、设计交付和跨职能协作。",
      resumeCapabilitySixTitle: "语言",
      resumeCapabilitySixBody: "普通话（母语）、英语（流利）和日语（基础）。",
    },
    ja: {
      navResume: "CV",
      viewResume: "CVを見る",
      readResume: "CVを読む",
      closeResume: "CVを閉じる",
      resumeTopline: "Curriculum Vitae（CV）",
      printResume: "CVを印刷 / PDF保存",
      resumeFocus: "UXリサーチ | インタラクションデザイン | ヒューマン・コンピュータ・インタラクション",
      resumeSummary: "メルボルン大学デザイン学士課程に在籍し、応用心理学、UXリサーチ、インタラクションデザイン、混合研究法の履修と実践経験があります。質問紙作成、インタビュー、ユーザビリティテスト、調査データのクリーニング、初期的な記述分析、自由記述のコーディング、研究報告、Figmaによるインタラクティブなプロトタイピングに取り組んできました。",
      resumeProfileTitle: "研究プロフィール",
      resumeProfileOne: "メルボルン大学デザイン学士課程に在籍し、応用心理学、UXリサーチ、インタラクションデザイン、混合研究法の履修と実践経験があります。質問紙作成、インタビュー、ユーザビリティテスト、調査データのクリーニング、初期的な記述分析、自由記述のコーディング、研究報告、Figmaによるインタラクティブなプロトタイピングに取り組んできました。",
      resumeProfileTwo: "今後の研究方向は、日々の変化が小さく気づきにくいとき、人が自分の身体の段階的な変化をどのように知覚できるか、という身体的インタラクションへの関心から生まれています。過去の運動負荷に関係する身体状態を記録・校正し、複数のセッションにわたって再提示することで、リハビリテーションの進捗を知覚しやすくできるかを検討したいと考えています。これは今後取り組みたい研究であり、すでに完了した研究ではありません。大学院では、ウェアラブルセンシング、心理物理学、触覚プロトタイピング、縦断評価、研究倫理に必要な能力を身につけ、技術的な校正と健康な成人を対象とした研究から始めた上で、リハビリテーションへの適用可能性を検討したいと考えています。",
      educationTitle: "学歴",
      educationOneDate: "2024年2月 - 2027年2月修了予定",
      educationOneDegree: "メルボルン大学 | デザイン学士",
      educationOnePlace: "オーストラリア・メルボルン",
      educationOneFocus: "専攻領域：ヒューマン・コンピュータ・インタラクション、ユーザーエクスペリエンスデザイン。",
      educationOneBody: "関連科目：ユーザーリサーチ、定量・定性研究、ユーザビリティ評価、ウェブ・インタラクションデザイン、金融、ビジネス。",
      educationTwoDate: "2025年7月 - 2025年8月",
      educationTwoDegree: "高麗大学 | 短期交換留学",
      educationTwoPlace: "韓国・ソウル",
      educationTwoBody: "異文化学習と国際的な学術経験。",
      educationThreeDate: "2026年1月 - 2026年2月",
      educationThreeDegree: "立命館大学 | 短期交換留学",
      educationThreePlace: "日本・京都",
      educationThreeBody: "国際的な学習環境で、日本語と日本文化を学びました。",
      experienceTitle: "研究・関連経験",
      experienceOneDate: "2026年2月 - 2026年6月",
      experienceOneRole: "HCIリサーチアシスタント",
      experienceOnePlace: "メルボルン大学",
      experienceOneSubtitle: "AI支援教育と学生の授業体験に関する研究プロジェクト",
      experienceOneBulletOne: "AIツールを大学教育へ取り入れ、学生の授業体験と教育の質を改善する方法を検討する教育研究プロジェクトを支援しました。",
      experienceOneBulletTwo: "定量尺度と自由記述項目を含む混合研究法の授業満足度質問紙の作成を補助し、回答の整理・クリーニング、初期的な記述分析、定性フィードバックのコーディングを行いました。",
      experienceOneBulletThree: "大学の研究会議に参加し、学生のフィードバックとAI支援学習に関するHCIの問いを結びつける図表、報告書草案、発表資料を作成しました。",
      experienceTwoDate: "2025年2月 - 2025年7月",
      experienceTwoRole: "UI/UXデザイン・インターン",
      experienceTwoPlace: "TidyTeddy",
      experienceTwoBulletOne: "TidyTeddyの清掃サービスサイトの更新と新機能開発に携わり、スケッチ、ボタン配置、ページ構成、ウェブとモバイルの低精細プロトタイプから作業を始めました。",
      experienceTwoBulletTwo: "承認されたフローをFigmaの高精細なウェブ・モバイルプロトタイプへ展開し、レスポンシブレイアウト、コンポーネント状態、ナビゲーション、引き渡し仕様を定義しました。",
      experienceTwoBulletThree: "ITチームとデザインの引き渡しおよび実装時のフィードバックを調整し、開発中に画面を修正して、更新サイトと新機能の正式公開を支援しました。",
      experienceThreeDate: "2026年5月 - 現在",
      experienceThreeRole: "プロダクトマネージャー / デジタルコンサルタント",
      experienceThreePlace: "Linghang Education & Migration Service",
      experienceThreeBulletOne: "留学・移住支援のバックオフィス業務を整理し、反復的な調査と書類作業を特定しました。UiPath/RPAとCodexを用いたAI支援プロセスを設計し、情報収集、確認、テンプレート利用、知識再利用に伴う手作業の削減に取り組みました。",
      experienceThreeBulletTwo: "顧客の目標、学歴、適格条件、日程、リスクをサービス選択肢とタスク計画へ変換して留学サービスパッケージを設計し、AI支援業務に出典確認、人による確認、プライバシー管理、例外処理を組み込みました。",
      resumeProjectsTitle: "主な研究プロジェクト",
      resumeProjectOneDate: "2026年2月 - 2026年6月",
      resumeProjectOneTitle: "AI支援教育と学生の授業体験に関する研究 | メルボルン大学",
      resumeProjectOneBulletOne: "学生の授業満足度とAIツールによる大学教育支援を検討する混合研究法の教育研究に参加し、評価項目と質問紙項目の構成を支援しました。",
      resumeProjectOneBulletTwo: "調査回答の整理・クリーニング、初期的な記述分析、自由記述のコーディングを行い、大学の研究会議に向けた図表、報告書草案、発表資料を作成しました。",
      resumeProjectTwoDate: "2024年 - 2026年",
      resumeProjectTwoTitle: "ユーザーリサーチと行動分析 | 大学課程",
      resumeProjectTwoBulletOne: "質問紙、インタビュー、観察、タスク分析を用い、デジタル製品やサービスにおける利用者の目標、行動、制約、満足度、意思決定経路を調べました。",
      resumeProjectTwoBulletTwo: "根拠をペルソナ、ジャーニーマップ、タスクフロー、課題、優先順位を付けた調査・設計機会へ整理しました。",
      resumeProjectThreeDate: "2024年 - 2026年",
      resumeProjectThreeTitle: "ユーザビリティ評価とアクセシビリティ | 大学課程",
      resumeProjectThreeBulletOne: "ユーザビリティテスト、ファーストクリックテスト、5秒テスト、カードソーティングを通じてウェブサイトとデジタルプラットフォームを評価し、タスク効率、誤り、摩擦、理解度を調べました。",
      resumeProjectThreeBulletTwo: "Nielsenのヒューリスティクス、WAIアクセシビリティ指針、ISO 9241の原則を用いて画面上の問題を診断し、設計提案の優先順位を付けました。",
      resumeProjectFourDate: "2024年 - 2026年",
      resumeProjectFourTitle: "ウェブインタラクションデザインとプロトタイピング | 大学課程",
      resumeProjectFourBulletOne: "Figmaで情報設計、レスポンシブページレイアウト、視覚階層、画面状態、インタラクションフローを設計しました。",
      resumeProjectFourBulletTwo: "インタラクティブなプロトタイプを制作・検証し、デザインと開発の連携に必要なHTML、CSS、JavaScriptの基礎知識を身につけました。",
      resumeProjectFiveDate: "2025年2月 - 2025年6月",
      resumeProjectFiveTitle: "定量的意思決定分析 | オーストラリア複数資産戦略",
      resumeProjectFiveBulletOne: "Excelでオーストラリアの10資産クラスについて2013-2024年の年次データを分析し、平均リターン、ボラティリティ、年平均成長率、シャープレシオ、金利ストレスシナリオを比較して、リスクを考慮した配分案を作成しました。",
      resumeProjectSixDate: "2025年 - 2026年",
      resumeProjectSixTitle: "人間とAIのワークフロー設計およびプロダクトテスト",
      resumeProjectSixBulletOne: "生成AIとRPAが情報収集、統合、テンプレート作成、視覚的検討、プロダクトテストをどのように支援できるかを、出典確認、人による確認、プライバシー保護、例外処理を維持しながら検討しました。",
      resumeCapabilitiesTitle: "研究・デザイン・技術スキル",
      resumeCapabilityOneTitle: "UXリサーチ",
      resumeCapabilityOneBody: "質問紙作成、定性インタビュー、観察、タスク分析、ユーザビリティテスト、ファーストクリックテスト、5秒テスト、カードソーティング、視線計測、アクセシビリティ評価。",
      resumeCapabilityTwoTitle: "インタラクションデザインとプロトタイピング",
      resumeCapabilityTwoBody: "ペルソナ、ジャーニーマップ、情報設計、ワイヤーフレーム、レスポンシブ画面設計、Figmaによるインタラクティブなプロトタイピング。",
      resumeCapabilityThreeTitle: "データ分析",
      resumeCapabilityThreeBody: "調査データのクリーニング、記述統計、自由記述のコーディング、テーマ分析、図表作成、Excelによるデータ可視化。",
      resumeCapabilityFourTitle: "プログラミングとAI自動化",
      resumeCapabilityFourBody: "HTML、CSS、JavaScript。AI支援ワークフロー設計、UiPath/RPA、Codex、ChatGPT、出典確認、人による確認、例外処理。",
      resumeCapabilityFiveTitle: "プロジェクト遂行",
      resumeCapabilityFiveBody: "調査計画、要件定義、研究会議、関係者との連絡、サービスジャーニー整理、デザイン引き渡し、部門横断での遂行。",
      resumeCapabilitySixTitle: "言語",
      resumeCapabilitySixBody: "中国語（母語）、英語（流暢）、日本語（基礎）。",
    },
  };

  for (const [language, copy] of Object.entries(cv)) {
    if (!global.PORTFOLIO_I18N?.[language]) continue;
    Object.assign(global.PORTFOLIO_I18N[language].site, copy);
    if (global.PORTFOLIO_I18N[language].ui) {
      global.PORTFOLIO_I18N[language].ui.resumeLabel = language === "en" ? "Curriculum Vitae" : "CV";
    }
  }
})(window);
